services:
  - type: web
    name: User-Service
    env: docker
    buildCommand: mvn clean install
    startCommand: java -jar /app.jar
    context: User-Service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
